LOAD DATA INFILE data
    INTO TABLE SUPPLEMENTARY_DEMOGRAPHICS
    INSERT
    FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
(CUST_ID,
 EDUCATION,
 OCCUPATION,
 HOUSEHOLD_SIZE,
 YRS_RESIDENCE,
 AFFINITY_CARD,
 BULK_PACK_DISKETTES,
 FLAT_PANEL_MONITOR,
 HOME_THEATER_PACKAGE,
 BOOKKEEPING_APPLICATION,
 PRINTER_SUPPLIES,
 Y_BOX_GAMES,
 OS_DOC_SET_KANJI,
COMMENTS)