SET ECHO ON
HOST mkdir /u02/app/oracle/oradata/ORCL/pdb19

ALTER PLUGGABLE DATABASE pdb19 CLOSE;
ALTER SESSION SET db_create_file_dest='/u02/app/oracle/oradata/ORCL/pdb19';
DROP PLUGGABLE DATABASE pdb19 INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE pdb19
    ADMIN USER pdb_admin IDENTIFIED BY Welcome_1 ROLES=(CONNECT)
    CREATE_FILE_DEST='/u02/app/oracle/oradata/ORCL/pdb19';
	
ALTER PLUGGABLE DATABASE pdb19 OPEN;
exit
