#!/bin/sh
#  -- DISCLAIMER:
#  -- This script is provided for educational purposes only. It is
#  -- NOT supported by Oracle World Wide Technical Support.
#  -- The script has been tested and appears to work as intended.
#  -- You should always run new scripts on a test instance initially.
#  -- Run as ORACLE OS user

# This script scrambles the data in the BARCOPY and BARDEPT
# tables in preparation for a FLASHBACK TABLE or Transaction
# Operation.
# Scramble department names, and department assignments

sleep 30

sqlplus sys/cloud_4U@orclpdb1 as sysdba > /home/oracle/labs/DBMod_Flashback/break.log <<EOF

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'ADMIRATION'
 	WHERE DEPARTMENT_ID = 10;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'MACAROONS'
 	WHERE DEPARTMENT_ID = 20;
 
  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PUSHBROOMS'
 	WHERE DEPARTMENT_ID = 30;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'HUMAN REPRISAL'
 	WHERE DEPARTMENT_ID = 40;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'SCHLEPPING'
 	WHERE DEPARTMENT_ID = 50;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'INFORMATION MANAGLING'
 	WHERE DEPARTMENT_ID = 60;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PUBLIC REVULSION'
 	WHERE DEPARTMENT_ID = 70;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'SAILORS'
 	WHERE DEPARTMENT_ID = 80;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'EXECUTION'
 	WHERE DEPARTMENT_ID = 90;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'FRUSTRATION'
 	WHERE DEPARTMENT_ID = 100;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'BEAN COUNTING'
 	WHERE DEPARTMENT_ID = 110;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PIGGY BANK'
 	WHERE DEPARTMENT_ID = 120;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'DUCKING'
 	WHERE DEPARTMENT_ID = 130;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'CORRUPTION'
 	WHERE DEPARTMENT_ID = 140;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'LIVESTOCK'
 	WHERE DEPARTMENT_ID = 150;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'BODKIN'
 	WHERE DEPARTMENT_ID = 160;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'MISCHIEF'
 	WHERE DEPARTMENT_ID = 170;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'CONFUSION'
 	WHERE DEPARTMENT_ID = 180;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PAPER PUSHING'
 	WHERE DEPARTMENT_ID = 190;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'SURGERY'
 	WHERE DEPARTMENT_ID = 200;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'IT SUPPRESSION'
 	WHERE DEPARTMENT_ID = 210;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'NO OBVIOUS CLUE'
 	WHERE DEPARTMENT_ID = 220;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'OBFUSCATION'
 	WHERE DEPARTMENT_ID = 230;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'EXTORTION'
 	WHERE DEPARTMENT_ID = 240;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'SCALPING'
 	WHERE DEPARTMENT_ID = 250;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PROCUREMENT'
 	WHERE DEPARTMENT_ID = 260;

  UPDATE BAR.BARDEPT SET DEPARTMENT_NAME = 'PUNISHMENT'
 	WHERE DEPARTMENT_ID = 270;

DECLARE
   CURSOR C1 is
	SELECT * FROM BAR.BARCOPY FOR UPDATE;
BEGIN 

FOR C1_row IN C1 LOOP
  UPDATE BAR.BARCOPY SET DEPARTMENT_ID =
    (SELECT TRUNC(DBMS_RANDOM.VALUE(10,270),-1) FROM DUAL)
    WHERE CURRENT OF C1;
END LOOP;

END;
/

COMMIT;
EOF
echo "DML executed." >> /home/oracle/labs/DBMod_Flashback/break.log
exit
