SELECT e.EXTENSION expression, t.NUM_DISTINCT, t.HISTOGRAM FROM	USER_STAT_EXTENSIONS e, USER_TAB_COL_STATISTICS t WHERE e.EXTENSION_NAME=t.COLUMN_NAME
AND	e.TABLE_NAME=t.TABLE_NAME
AND	t.TABLE_NAME='CUSTOMERS';
