set echo on

CREATE INDEX CUST_CUST_GENDER_idx
ON CUSTOMERS(CUST_GENDER)
NOLOGGING COMPUTE STATISTICS;

CREATE INDEX CUST_CUST_POSTAL_CODE_idx
ON CUSTOMERS(CUST_POSTAL_CODE)
NOLOGGING COMPUTE STATISTICS;

CREATE INDEX CUST_CUST_CREDIT_LIMIT_idx
ON CUSTOMERS(CUST_CREDIT_LIMIT)
NOLOGGING COMPUTE STATISTICS;

