set echo on
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE CONTAINER=ALL ;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY Welcome_1 CONTAINER=ALL;
ALTER SYSTEM SET wallet_root = '/u01/app/oracle/admin/ORCL/tde_keystore'
       SCOPE=SPFILE;
exit
