LOAD DATA INFILE dat
   DISCARDFILE  SH.CHANNELS.discard
   DISCARDMAX  200
    INTO TABLE SH.CHANNELS
    INSERT
    FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
(CHANNEL_ID,
 CHANNEL_DESC,
 CHANNEL_CLASS,
 CHANNEL_TOTAL)
