--
-- Copyright (c) 2003 Oracle Corporation. All rights reserved.
--
LOAD APPEND
INTO TABLE odm_build 
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'( 
AGE,WORKCLASS,ANNUAL_INCOME,EDUCATION,WKS_SINCE_LAST_PURCH,MARITAL_STATUS,OCCUPATION, HOUSEHOLD_SIZE, TOP_REASON_FOR_SHOPPING, GENDER, SHIPPING_ADDRESS_COUNTRY, AFFINITY_CARD, AVERAGE_ITEMS_PURCHASED , NO_DIFFERENT_KIND_ITEMS , BULK_PURCH_AVE_AMT , YRS_RESIDENCE , DISABLE_COOKIES, PROMO_RESPOND, MAILING_LIST, SR_CITIZEN, COLD_FLU, PAIN_FEVER, VITAMINS, BABY, COSMETICS, GIFTS, FOOD_CANDY, PETS,CASE_ID)
