LOAD DATA
APPEND
INTO TABLE products
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '^'
(PROD_ID,
 PROD_NAME,
 PROD_DESC,
 PROD_SUBCATEGORY,
 PROD_SUBCATEGORY_ID,
 PROD_SUBCATEGORY_DESC,
 PROD_CATEGORY,
 PROD_CATEGORY_ID,
 PROD_CATEGORY_DESC,
 PROD_WEIGHT_CLASS,
 PROD_UNIT_OF_MEASURE,
 PROD_PACK_SIZE,
 SUPPLIER_ID,
 PROD_STATUS,
 PROD_LIST_PRICE,
 PROD_MIN_PRICE,
 PROD_TOTAL,
 PROD_TOTAL_ID,
 COMPANY_ID FILLER,
 PROD_SRC_ID,
 PROD_EFF_FROM DATE(10) "YYYY-MM-DD",
 PROD_EFF_TO DATE(10) "YYYY-MM-DD",
 PROD_VALID)
