LOAD DATA 
    INTO TABLE PRODUCTS
    INSERT
    FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '^'
(PROD_ID,
 PROD_NAME,
 PROD_DESC,
 PROD_SUBCATEGORY,
 PROD_SUBCATEGORY_ID,
 PROD_SUBCATEGORY_DESC,
 PROD_CATEGORY,
 PROD_CATEGORY_ID,
 PROD_CATEGORY_DESC,
 PROD_WEIGHT_CLASS,
 PROD_UNIT_OF_MEASURE,
 PROD_PACK_SIZE,
 SUPPLIER_ID,
 PROD_STATUS,
 PROD_LIST_PRICE "TO_NUMBER(:PROD_LIST_PRICE,'99999999.99')",
 PROD_MIN_PRICE "TO_NUMBER(:PROD_MIN_PRICE,'99999999.99')",
 PROD_TOTAL,
 PROD_TOTAL_ID,
 PROD_SRC_ID,
 PROD_EFF_FROM DATE(19) "YYYY-MM-DD-HH24-MI-SS",
 PROD_EFF_TO DATE(19) "YYYY-MM-DD-HH24-MI-SS",
 PROD_VALID)
