set echo on
HOST mkdir /u02/app/oracle/oradata/CDB19/PDB19

ALTER PLUGGABLE DATABASE pdb19 CLOSE;
ALTER SESSION SET db_create_file_dest='/u02/app/oracle/oradata/CDB19/PDB19';
DROP PLUGGABLE DATABASE pdb19 INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE pdb19
    ADMIN USER pdb_admin IDENTIFIED BY Welcome_1 ROLES=(CONNECT)
    CREATE_FILE_DEST='/u02/app/oracle/oradata/CDB19/PDB19';
ALTER PLUGGABLE DATABASE pdb19 OPEN;

ALTER SESSION SET CONTAINER=pdb19;

ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY Welcome_1;
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY Welcome_1 WITH BACKUP;

CREATE DIRECTORY dp_pdb19 AS '/tmp';
CREATE USER hr IDENTIFIED BY Welcome_1;
GRANT read, write ON DIRECTORY dp_pdb19 TO hr;
GRANT create session, create table TO hr;

DROP TABLESPACE test INCLUDING CONTENTS AND DATAFILES;
ALTER SESSION SET db_create_file_dest='';
CREATE TABLESPACE test DATAFILE '/u02/app/oracle/oradata/CDB19/PDB19/test01.dbf' SIZE 10M  encryption using 'AES256' default storage(encrypt);

exit
