set echo on
ALTER SYSTEM RESET wallet_root  SCOPE=SPFILE;
ALTER SYSTEM RESET tde_configuration SCOPE=BOTH;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY Welcome_1 CONTAINER = ALL;

exit
