set echo on
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT  /*+ Full */  /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT   /*+ Full */ count(*)   FROM  OE.supplier ;
exit

