SET ECHO ON
DROP USER moni CASCADE;
DROP USER sqldev CASCADE;

DROP TABLESPACE moni_tbs INCLUDING CONTENTS;

CREATE SMALLFILE TABLESPACE moni_tbs 
   DATAFILE '/u02/app/oracle/oradata/ORCL/pdb1/moni01.dbf' 
   SIZE 100M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE 32767M NOLOGGING 
   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER moni IDENTIFIED BY Welcome_1 
   DEFAULT TABLESPACE moni_tbs TEMPORARY TABLESPACE temp;
CREATE USER sqldev IDENTIFIED BY Welcome_1;

GRANT create session TO sqldev, moni;
GRANT create table, unlimited tablespace TO moni;

EXIT