INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (7,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (8,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (9,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (10,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (11,'Memoptwrites');
COMMIT;

