set echo on
DROP TABLESPACE users INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE users DATAFILE '/u02/app/oracle/oradata/ORCL/users01.dbf' SIZE 70M AUTOEXTEND ON;
CREATE TABLESPACE users AUTOEXTEND ON;
exit
