LOAD DATA
APPEND

INTO TABLE customers
FIELDS TERMINATED BY "|"
( CUST_ID,
 CUST_FIRST_NAME, CUST_LAST_NAME, CUST_GENDER,
 CUST_YEAR_OF_BIRTH, CUST_MARITAL_STATUS,
 CUST_STREET_ADDRESS, CUST_POSTAL_CODE, CUST_CITY,
 CUST_STATE_PROVINCE, COUNTRY_ID,
 CUST_MAIN_PHONE_NUMBER, CUST_INCOME_LEVEL,
 CUST_CREDIT_LIMIT, CUST_EMAIL)

