LOAD DATA
APPEND

INTO TABLE products
FIELDS TERMINATED BY "|"
( PROD_ID,
 PROD_NAME, PROD_DESC, PROD_SUBCATEGORY, PROD_SUBCAT_DESC,
 PROD_CATEGORY, PROD_CAT_DESC, PROD_WEIGHT_CLASS,
 PROD_UNIT_OF_MEASURE, PROD_PACK_SIZE, SUPPLIER_ID,
 PROD_STATUS, PROD_LIST_PRICE, PROD_MIN_PRICE)
