set echo on
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY Welcome_1 CONTAINER = ALL;

ALTER SYSTEM RESET wallet_root SCOPE=SPFILE;
ALTER SYSTEM RESET tde_configuration SCOPE=BOTH;
ALTER SYSTEM set encrypt_new_tablespaces='DDL' scope=both;

shutdown immediate

host rm -rf  /u02/app/oracle/admin/ORCL/tde_wallet
host rm -rf  /u02/app/oracle/admin/ORCL/tde_keystore
host rm -rf /u01/app/oracle/admin/ORCL/tde_keystore
host mkdir -p  /u02/app/oracle/admin/ORCL/tde_wallet

startup
ALTER PLUGGABLE DATABASE pdb1 OPEN;
ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/u02/app/oracle/admin/ORCL/tde_wallet' IDENTIFIED BY Welcome_1;
ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY Welcome_1 CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY Welcome_1 WITH BACKUP CONTAINER = ALL;

ALTER SESSION SET CONTAINER=pdb1;

ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY Welcome_1;
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY Welcome_1 WITH BACKUP;

ALTER SYSTEM SET db_create_file_dest='';
DROP TABLESPACE omts_tbs INCLUDING CONTENTS and DATAFILES;
CREATE TABLESPACE omts_tbs DATAFILE '/u02/app/oracle/oradata/ORCL/PDB1/omts01.dbf' SIZE 10M ENCRYPTION USING 'AES192' ENCRYPT ;
exit
