Set echo on
startup

DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE pdb1 ADMIN USER pdb_admin IDENTIFIED BY Welcome_1 ROLES=(CONNECT)
   CREATE_FILE_DEST='/u02/app/oracle/oradata/ORCL/pdb1';
ALTER PLUGGABLE DATABASE pdb1 open;

ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/u02/app/oracle/admin/ORCL/tde_wallet' IDENTIFIED BY Welcome_1;
ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY Welcome_1 CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY Welcome_1 WITH BACKUP CONTAINER = ALL;
exit