LOAD DATA
APPEND

INTO TABLE costs
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
(COMPANY_ID FILLER,
 PROD_ID,
 TIME_ID DATE(10) "YYYY-MM-DD",
 UNIT_COST "TO_NUMBER(:UNIT_COST,'99999999.99')",
 UNIT_PRICE) "TO_NUMBER(:UNIT_PRICE,'99999999.99')")

