LOAD DATA INFILE dat
   DISCARDFILE  SH.COUNTRIES.discard
   DISCARDMAX  200
    INTO TABLE SH.COUNTRIES
    INSERT
    FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
(COUNTRY_ID,
 COUNTRY_NAME,
 COUNTRY_SUBREGION,
 COUNTRY_REGION,
 COUNTRY_TOTAL)
