LOAD DATA
INTO TABLE COUNTRIES
APPEND
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
(COUNTRY_ID,
 COUNTRY_ISO_CODE,
 COUNTRY_NAME,
 COUNTRY_SUBREGION,
 COUNTRY_SUBREGION_ID,
 COUNTRY_REGION,
 COUNTRY_REGION_ID,
 COUNTRY_TOTAL,
 COUNTRY_TOTAL_ID)
