SET ECHO ON
ALTER DATABASE FLASHBACK OFF;
ALTER PLUGGABLE DATABASE ALL CLOSE;
DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE pdb2 INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE pdb19_in_orcl INCLUDING DATAFILES;

EXIT