set echo on
DROP USER hr CASCADE;
CREATE USER hr IDENTIFIED BY Welcome_1;
GRANT dba TO hr;

CREATE TABLE hr.tabflash (c1 NUMBER, c2 CHAR (100));
INSERT INTO  hr.tabflash VALUES (1,'B');
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
INSERT INTO  hr.tabflash VALUES (2,'D');
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
UPDATE hr.tabflash SET c1=c1*10;
COMMIT;
INSERT INTO  hr.tabflash VALUES (3,'B');
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
INSERT INTO  hr.tabflash VALUES (4,'D');
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
UPDATE hr.tabflash SET c1=c1*20;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
INSERT INTO  hr.tabflash SELECT * FROM hr.tabflash;
COMMIT;
UPDATE hr.tabflash SET c1=c1*30;
COMMIT;
UPDATE hr.tabflash SET c1=c1+43;
COMMIT;
UPDATE hr.tabflash SET c1=c1+5;
COMMIT;
UPDATE hr.tabflash SET c1=c1+6;
COMMIT;
UPDATE hr.tabflash SET c1=c1+7;
COMMIT;
UPDATE hr.tabflash SET c1=c1+8;
COMMIT;
UPDATE hr.tabflash SET c1=c1+9;
COMMIT;
UPDATE hr.tabflash SET c1=c1+10;
COMMIT;
UPDATE hr.tabflash SET c1=c1+11;
COMMIT;
UPDATE hr.tabflash SET c1=c1+12;
COMMIT;

EXIT