set echo on
INSERT INTO hr.t VALUES (1,1);
INSERT INTO hr.t VALUES (1,2);
INSERT INTO hr.t VALUES (1,3);
INSERT INTO hr.t VALUES (1,3);
INSERT INTO hr.t VALUES (2,1);
INSERT INTO hr.t VALUES (2,2);
INSERT INTO hr.t VALUES (2,2);
INSERT INTO hr.t VALUES (2,3);
INSERT INTO hr.t VALUES (3,1);
INSERT INTO hr.t VALUES (3,2);
INSERT INTO hr.t VALUES (3,2);
COMMIT;
