rem 
GRANT dba TO hr;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (2,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (3,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (4,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (5,'Memoptwrites');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites SELECT * FROM  hr.memoptwrites ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptwrites VALUES (6,'Memoptwrites');
COMMIT;

