set echo on
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw VALUES (0,'Memoptw');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw VALUES (2,'Memoptw');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw VALUES (3,'memoptw');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw VALUES (4,'memoptw');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw VALUES (11,'Memoptw');
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
INSERT /*+ MEMOPTIMIZE_WRITE */ INTO hr.memoptw SELECT * FROM  hr.memoptw ;
COMMIT;

