set echo on

ALTER INDEX CUSTOMERS_PK MONITORING USAGE;

ALTER INDEX CUST_CUST_POSTAL_CODE_IDX MONITORING USAGE;

ALTER INDEX CUST_CUST_GENDER_IDX MONITORING USAGE;

ALTER INDEX CUST_CUST_CREDIT_LIMIT_IDX MONITORING USAGE;

